services:
  - type: web
    name: flashnotify
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -c "from app import init_db; init_db()" && gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
